services:

  mysql:
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
    secrets:
      - root_password
      - user_password

  phpmyadmin:
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql

secrets:
  user_password:
    file: ./secrets/user_password.txt
  root_password:
    file: ./secrets/root_password.txt